.github/workflows/integration_tests.yaml, .github/workflows/shared_integration_tests.yaml, gen3-integration-tests/README.md, gen3-integration-tests/conftest.py, gen3-integration-tests/gen3_ci/scripts/prepare_ci_environment.py, gen3-integration-tests/gen3_ci/scripts/release_ci_environment.py, gen3-integration-tests/gen3_ci/scripts/save_ci_env_pod_logs.py, gen3-integration-tests/gen3_ci/scripts/select_ci_environment.py, gen3-integration-tests/services/fence.py, gen3-integration-tests/services/metadataservice.py, gen3-integration-tests/tests/api/test_aggregate_mds.py, gen3-integration-tests/utils/gen3_admin_tasks.py, gen3-integration-tests/utils/jenkins.py
Jira Ticket: [GQE-137](https://ctds-planx.atlassian.net/browse/GQE-137)
[GQE-137]: https://ctds-planx.atlassian.net/browse/GQE-137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add documentation

.github/workflows/shared_integration_tests.yaml, gen3-integration-tests/pyproject.toml, gen3-integration-tests/tests/api/test_aggregate_mds.py
Jira Ticket: [GQE-145](https://ctds-planx.atlassian.net/browse/GQE-145)
[GQE-145]: https://ctds-planx.atlassian.net/browse/GQE-145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Support running tests for specific service

.github/workflows/integration_tests.yaml, .github/workflows/shared_integration_tests.yaml, gen3-integration-tests/services/fence.py
=> Fix workflow to use org-level secrets

.github/workflows/shared_integration_tests.yaml, gen3-integration-tests/gen3_ci/scripts/clean_up_jenkins.py, gen3-integration-tests/gen3_ci/scripts/prepare_ci_environment.py, gen3-integration-tests/gen3_ci/scripts/release_ci_environment.py, gen3-integration-tests/gen3_ci/scripts/save_ci_env_pod_logs.py, gen3-integration-tests/gen3_ci/scripts/select_ci_environment.py, gen3-integration-tests/utils/gen3_admin_tasks.py, gen3-integration-tests/utils/jenkins.py
Jira Ticket: [GQE-143](https://ctds-planx.atlassian.net/browse/GQE-143)
[GQE-143]: https://ctds-planx.atlassian.net/browse/GQE-143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Clean up timed out and pending jenkins jobs

.github/workflows/shared_integration_tests.yaml, .gitignore, gen3-integration-tests/README.md, gen3-integration-tests/conftest.py, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fetch-configs.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-generate-api-key.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-modify-env-for-service-pr.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-modify-env-for-test-repo-pr.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-run-gen3-command.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-save-pod-logs.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-select-and-lock-namespace.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-unlock-namespace.groovy, gen3-integration-tests/gen3_ci/scripts/clean_up_jenkins.py, gen3-integration-tests/services/fence.py, gen3-integration-tests/utils/gen3_admin_tasks.py, gen3-integration-tests/utils/jenkins.py
- Fetch `manifest.json` from admin VM so tests can access configurations
- More error handling for running jenkins jobs and fetching artifacts
=> Fetch manifest.json + more error handling

.github/workflows/integration_tests.yaml, .github/workflows/shared_integration_tests.yaml
- CI pipeline improvements: run clean-up steps even when previous steps fail, and do not run tests on Readme updates
=> CI pipeline improvements

gen3-integration-tests/README.md
Jira Ticket: [GQE-162](https://ctds-planx.atlassian.net/browse/GQE-162)
[GQE-162]: https://ctds-planx.atlassian.net/browse/GQE-162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update README.md - jenkins job names changed

.github/workflows/shared_integration_tests.yaml, gen3-integration-tests/gen3_ci/scripts/prepare_ci_environment.py, gen3-integration-tests/gen3_ci/scripts/release_ci_environment.py, gen3-integration-tests/gen3_ci/scripts/save_ci_env_pod_logs.py, gen3-integration-tests/gen3_ci/scripts/select_ci_environment.py, gen3-integration-tests/utils/gen3_admin_tasks.py, gen3-integration-tests/utils/jenkins.py
- More error handling
- Pipeline always releases CI environment, regardless of success, failure or cancelation
=> Error handling + pipeline always releases CI environment

gen3-integration-tests/gen3_ci/jenkins_jobs/generate_api_keys.groovy
=> Update generate_api_keys.groovy - auxAcct users api generation

gen3-integration-tests/conftest.py
=> Prevent multiple runs of configuration file generation

gen3-integration-tests/gen3_ci/jenkins_jobs/generate_api_keys.groovy
Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)
=> Generate api-key for user0

gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fetch-configs.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-generate-api-key.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-modify-env-for-service-pr.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-modify-env-for-test-repo-pr.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-run-gen3-command.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-run-gen3-job.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-save-pod-logs.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-select-and-lock-namespace.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-unlock-namespace.groovy
Jira Ticket: [GQE-183](https://ctds-planx.atlassian.net/browse/GQE-183)
[GQE-183]: https://ctds-planx.atlassian.net/browse/GQE-183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Increase resources for jenkins worker pods

gen3-integration-tests/pyproject.toml, gen3-integration-tests/services/audit.py, gen3-integration-tests/services/manifestservice.py, gen3-integration-tests/tests/api/test_audit_service.py, gen3-integration-tests/tests/api/test_manifest_service.py
Link to JIRA ticket if there is one: [GQE-189](https://ctds-planx.atlassian.net/browse/GQE-189)
[GQE-189]: https://ctds-planx.atlassian.net/browse/GQE-189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Migrate manifest service tests

gen3-integration-tests/README.md, gen3-integration-tests/conftest.py, gen3-integration-tests/pages/gen3ff_landing_page.py, gen3-integration-tests/pyproject.toml, gen3-integration-tests/tests/portal/test_gen3ff_landing_page.py
Link to JIRA ticket if there is one: [GQE-192](https://ctds-planx.atlassian.net/browse/GQE-192)
[GQE-192]: https://ctds-planx.atlassian.net/browse/GQE-192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Migrate frontend framework tests

.secrets.baseline, gen3-integration-tests/pages/login.py, gen3-integration-tests/tests/api/test_aggregate_mds.py, gen3-integration-tests/tests/api/test_audit_service.py, gen3-integration-tests/tests/api/test_client_credentials.py, gen3-integration-tests/tests/api/test_graph_submit_and_query.py, gen3-integration-tests/tests/portal/test_homepage.py, gen3-integration-tests/tests/portal/test_workspace.py
Link to JIRA ticket if there is one: [GQE-190](https://ctds-planx.atlassian.net/browse/GQE-190?atlOrigin=eyJpIjoiYmY3ZTFlYTQ1NDlkNGFmNzgwZDM3Y2VhZmNjZjIyODQiLCJwIjoiaiJ9) [GQE-199](https://ctds-planx.atlassian.net/browse/GQE-199?atlOrigin=eyJpIjoiNjBkNzMwNjI3ZWQxNGQ3NTkwNzllMGVlZWE2OWNlM2IiLCJwIjoiaiJ9)
[GQE-190]: https://ctds-planx.atlassian.net/browse/GQE-190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GQE-199]: https://ctds-planx.atlassian.net/browse/GQE-199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GQE-190 Updated testcase steps

.secrets.baseline, gen3-integration-tests/services/audit.py, gen3-integration-tests/tests/api/test_audit_service.py
=> Changes for RAS ORCID multiple records issue

.github/workflows/shared_integration_tests.yaml
=> Add QUAY_REPO as env

.github/workflows/shared_integration_tests.yaml, gen3-integration-tests/pyproject.toml
We are using `github.event.pull_request.labels` which only contains the labels at the time the PR was created. Labels added later are not fetched.
=> Fetch latest PR labels

.github/workflows/shared_integration_tests.yaml
=> Get the time of the last commit

.github/workflows/integration_tests.yaml, .github/workflows/shared_integration_tests.yaml, gen3-integration-tests/README.md
Link to JIRA ticket if there is one: [GQE-138](https://ctds-planx.atlassian.net/browse/GQE-138)
[GQE-138]: https://ctds-planx.atlassian.net/browse/GQE-138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Skip CI for specific labels and PRs with only md file changes

gen3-integration-tests/pyproject.toml, gen3-integration-tests/services/metadataservice.py, gen3-integration-tests/tests/test_aggregate_mds.py, gen3-integration-tests/tests/test_discoverypage.py, gen3-integration-tests/tests/test_metadata_ingestion.py
=> Test migration - metadataservice

gen3-integration-tests/gen3_ci/scripts/clean_up_jenkins.py, gen3-integration-tests/utils/jenkins.py
Link to JIRA ticket if there is one: [GQE-223](https://ctds-planx.atlassian.net/browse/GQE-223)
[GQE-223]: https://ctds-planx.atlassian.net/browse/GQE-223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix pipeline issues

gen3-integration-tests/pages/exploration.py, gen3-integration-tests/pyproject.toml, gen3-integration-tests/tests/test_pfb_export.py
Link to JIRA ticket if there is one: [GQE-239](https://ctds-planx.atlassian.net/browse/GQE-239)
[GQE-239]: https://ctds-planx.atlassian.net/browse/GQE-239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix test labels

.secrets.baseline, gen3-integration-tests/pages/login.py, gen3-integration-tests/pages/workspace.py, gen3-integration-tests/tests/test_aggregate_mds.py, gen3-integration-tests/tests/test_ras_drs.py, gen3-integration-tests/utils/test_execution.py
Link to JIRA ticket if there is one: [GQE-260](https://ctds-planx.atlassian.net/browse/GQE-260)
[GQE-260]: https://ctds-planx.atlassian.net/browse/GQE-260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Migration Fix - Indexd Ras DRS

gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-generate-api-key.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/fence-create-client.groovy, gen3-integration-tests/gen3_ci/scripts/prepare_ci_environment.py
=> Wait for usersync job to complete after fence client creation

gen3-integration-tests/gen3_ci/jenkins_jobs/fence-force-link-google.groovy, gen3-integration-tests/services/fence.py, gen3-integration-tests/tests/test_link_google_account.py, gen3-integration-tests/utils/gen3_admin_tasks.py
=> Migrate Link Google Account Tests

gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-modify-env-for-service-pr.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-modify-env-for-test-repo-pr.groovy, gen3-integration-tests/pages/login.py, gen3-integration-tests/pages/workspace.py, gen3-integration-tests/tests/test_audit_service.py, gen3-integration-tests/tests/test_client_credentials.py, gen3-integration-tests/tests/test_dbgap.py, gen3-integration-tests/tests/test_discoverypage.py, gen3-integration-tests/tests/test_ras_drs.py, gen3-integration-tests/tests/test_study_viewer.py
=> Skip RAS DRS test cases and remove object from indexd record

gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-audit-service-logging.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-check_indices_after_etl.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-clean-up-indices.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-client-rotate.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-create-client.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-disable-register-users-redirect.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-enable-register-users-redirect.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fetch-configs.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-modify-env-for-service-pr.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-modify-env-for-test-repo-pr.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-run-gen3-job.groovy
=> Update namespace for kubectl commands

gen3-integration-tests/pages/login.py
=> Fix Username Lookup when useProfileDropdown is enabled

gen3-integration-tests/conftest.py, gen3-integration-tests/gen3_ci/scripts/save_ci_env_pod_logs.py, gen3-integration-tests/list_test_suites.py
=> Collect test suites list

gen3-integration-tests/services/fence.py, gen3-integration-tests/utils/gen3_admin_tasks.py
Link to JIRA ticket if there is one: [GQE-286](https://ctds-planx.atlassian.net/browse/GQE-286)
[GQE-286]: https://ctds-planx.atlassian.net/browse/GQE-286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Helm Change for Revoke Arborist Policy

gen3-integration-tests/test_data/test_setup/guppy_es_indexes/es_indexes_data/configs_alias.json, gen3-integration-tests/test_data/test_setup/guppy_es_indexes/es_indexes_data/file_alias.json, gen3-integration-tests/test_data/test_setup/guppy_es_indexes/es_indexes_data/subject_alias.json, gen3-integration-tests/utils/gen3_admin_tasks.py
Link to JIRA ticket if there is one: [GQE-309](https://ctds-planx.atlassian.net/browse/GQE-309)
[GQE-309]: https://ctds-planx.atlassian.net/browse/GQE-309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Helm ETL Suite Changes

gen3-integration-tests/pages/login.py, gen3-integration-tests/services/audit.py
=> Fix Logged in User Case Issue

gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-generate-api-keys.groovy
Link to JIRA ticket if there is one: 
OOM errors (exit code 137) were noticed in this job runs. Increasing the resources for the shell container as a potential mitigation
=> Mitigating OOM errors in the job

.github/workflows/shared_integration_tests.yaml, gen3-integration-tests/README.md
Link to JIRA ticket if there is one: [GQE-318](https://ctds-planx.atlassian.net/browse/GQE-318)
[GQE-318]: https://ctds-planx.atlassian.net/browse/GQE-318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix logic to skip tests for doc changes

gen3-integration-tests/utils/jenkins.py
Link to JIRA ticket if there is one: [GQE-316](https://ctds-planx.atlassian.net/browse/GQE-316)
[GQE-316]: https://ctds-planx.atlassian.net/browse/GQE-316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Wait for non-null build result after jenkins job completion

gen3-integration-tests/gen3_ci/scripts/select_ci_environment.py
Link to JIRA ticket if there is one: [GQE-245](https://ctds-planx.atlassian.net/browse/GQE-245)
[GQE-245]: https://ctds-planx.atlassian.net/browse/GQE-245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Retry fetching namespaces and wait longer to select CI env

gen3-integration-tests/conftest.py, gen3-integration-tests/services/fence.py, gen3-integration-tests/services/indexd.py, gen3-integration-tests/services/requestor.py, gen3-integration-tests/utils/test_setup.py
Link to JIRA ticket if there is one: [GQE-358](https://ctds-planx.atlassian.net/browse/GQE-358)
[GQE-358]: https://ctds-planx.atlassian.net/browse/GQE-358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update pytest.auth_headers with auth access_token headers

gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-modify-env-for-service-pr.groovy, gen3-integration-tests/gen3_ci/scripts/prepare_ci_environment.py
=> Changes for QUAY_REPO support for multiple repos

gen3-integration-tests/pages/submission.py, gen3-integration-tests/tests/test_data_upload.py
=> Clean up Data Upload Portal Test

.secrets.baseline, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-generate-api-keys.groovy, gen3-integration-tests/pages/login.py, gen3-integration-tests/services/audit.py, gen3-integration-tests/tests/test_audit_service.py, gen3-integration-tests/tests/test_ras_authn.py
Link to JIRA ticket if there is one: [GQE-382](https://ctds-planx.atlassian.net/browse/GQE-382)
[GQE-382]: https://ctds-planx.atlassian.net/browse/GQE-382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix Audit Services - RAS login issue

.secrets.baseline, gen3-integration-tests/services/fence.py, gen3-integration-tests/tests/test_dbgap.py, gen3-integration-tests/tests/test_google_data_access.py
Link to JIRA ticket if there is one: [GQE-384](https://ctds-planx.atlassian.net/browse/GQE-384)
[GQE-384]: https://ctds-planx.atlassian.net/browse/GQE-384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Change for Google SA Keys deletion

gen3-integration-tests/utils/test_setup.py
Link to JIRA ticket if there is one: [GQE-385](https://ctds-planx.atlassian.net/browse/GQE-385)
[GQE-385]: https://ctds-planx.atlassian.net/browse/GQE-385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Handle fence client id and secret retrieval issue

.github/workflows/image_build.yaml, gen3-integration-tests/Dockerfile
=> removing "build platform" so we can have arm images.

gen3-integration-tests/Dockerfile, gen3-integration-tests/scripts/helm/generate_api_keys.sh
We would like the script to be more verbose if it fails for helm testing.
=> creating a more verbose "generate_api_keys" script.

gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-audit-service-logging.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-check_indices_after_etl.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-clean-up-indices.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-create-access-token.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-create-link-google-test-buckets.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-delete-client.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-disable-register-users-redirect.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-enable-register-users-redirect.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-force-link-google.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-generate-api-key.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-generate-api-keys.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-kube-setup-service.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-mutate-manifest-for-guppy-test.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-revoke-arborist-policy.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-run-gen3-command.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-run-gen3-job.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-save-pod-logs.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-setup-fence-test-clients.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/generate-api-keys.groovy, gen3-integration-tests/utils/gen3_admin_tasks.py
Link to JIRA ticket if there is one: [GQE-394](https://ctds-planx.atlassian.net/browse/GQE-394)
[GQE-394]: https://ctds-planx.atlassian.net/browse/GQE-394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update manifest.json for gen3 command runs

gen3-integration-tests/test_data/aggregate_mds/study1.json, gen3-integration-tests/test_data/aggregate_mds/study2.json
=> Fix test data for DiscoveryPageTest on HEAL PRs

.github/workflows/integration_tests.yaml, .github/workflows/shared_integration_tests.yaml
=> Comment Error message on PR and slack

gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-audit-service-logging.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-check_indices_after_etl.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-clean-up-indices.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-create-access-token.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-create-link-google-test-buckets.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-delete-client.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-disable-register-users-redirect.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-enable-register-users-redirect.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-force-link-google.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-generate-api-key.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-generate-api-keys.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-kube-setup-service.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-mutate-manifest-for-guppy-test.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-revoke-arborist-policy.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-run-gen3-command.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-run-gen3-job.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-save-pod-logs.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-setup-fence-test-clients.groovy, gen3-integration-tests/gen3_ci/jenkins_jobs/generate-api-keys.groovy
=> Update groovy scripts to resolve manifest.json tube issue

gen3-integration-tests/services/fence.py, gen3-integration-tests/tests/test_data_upload.py
=> Fix Data Upload Multipart Issue

.github/workflows/shared_integration_tests.yaml
Link to JIRA ticket if there is one: [GQE-405](https://ctds-planx.atlassian.net/browse/GQE-405)
[GQE-405]: https://ctds-planx.atlassian.net/browse/GQE-405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ensure the PR is run under the same org as an Internal PR

.github/workflows/shared_integration_tests.yaml
Link to JIRA ticket if there is one: [GQE-410](https://ctds-planx.atlassian.net/browse/GQE-410)
[GQE-410]: https://ctds-planx.atlassian.net/browse/GQE-410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update slack version

gen3-integration-tests/pyproject.toml, gen3-integration-tests/tests/test_workspace.py
=> Update test_workspace.py - Hatchery Skip

gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-setup-fence-test-clients.groovy, gen3-integration-tests/gen3_ci/scripts/release_ci_environment.py, gen3-integration-tests/utils/gen3_admin_tasks.py, gen3-integration-tests/utils/jenkins.py
- Use a dynamic jenkins worker for `setup-fence-test-clients job`
- More detailed logs while waiting for job completion
=> "setup-fence-test-clients job" improvements

gen3-integration-tests/pages/dicom.py
Link to JIRA ticket if there is one: 
- DICOM tests: Take screenshot earlier for easier debugging, and wait before pages fully load before taking screenshots
=> DICOM tests: Take screenshot earlier

.github/workflows/shared_integration_tests.yaml
Link to JIRA ticket if there is one: 
- Adds link to login to qa.planx-pla.net for convenience to access test report
=> Add login for test report

gen3-integration-tests/pages/submission.py
Link to JIRA ticket if there is one: 
- Update submission button locator to use button text instead of type. If the portal page has a closable banner there will be two buttons visible on the page when test runs
=> update button locator for submission test

.github/workflows/shared_integration_tests.yaml, gen3-integration-tests/gen3_ci/scripts/generate_slack_report.py
Link to JIRA ticket if there is one: [GQE-411](https://ctds-planx.atlassian.net/browse/GQE-411)
[GQE-411]: https://ctds-planx.atlassian.net/browse/GQE-411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Handle nightly builds

gen3-integration-tests/gen3_ci/scripts/generate_slack_report.py
=> Fix slack reporting of nightly builds

.github/workflows/integration_tests.yaml
=> Run integration tests only on changes to gen3-integration-tests folder

gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-modify-env-for-manifest-pr.groovy
=> Increase resource limits for pods that modify envs for manifest PRs

.github/workflows/shared_integration_tests.yaml
Link to JIRA ticket if there is one: [GQE-425](https://ctds-planx.atlassian.net/browse/GQE-425)
[GQE-425]: https://ctds-planx.atlassian.net/browse/GQE-425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Skip tests for release notes PRs

.github/workflows/shared_integration_tests.yaml
=> Fix accidental comment from workflow

gen3-integration-tests/tests/test_data_upload.py
=> Update test_data_upload.py to skip if metadata service isnt running

gen3-integration-tests/conftest.py, gen3-integration-tests/pyproject.toml, gen3-integration-tests/services/userdatalibrary.py, gen3-integration-tests/tests/test_user_data_library.py
Link to JIRA ticket if there is one: [GQE-375](https://ctds-planx.atlassian.net/browse/GQE-375)
[GQE-375]: https://ctds-planx.atlassian.net/browse/GQE-375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Gen3-user-data-library Tests

.secrets.baseline, gen3-integration-tests/tests/test_audit_service.py, gen3-integration-tests/tests/test_ras_authn.py
Link to JIRA ticket if there is one: [GQE-432](https://ctds-planx.atlassian.net/browse/GQE-432)
[GQE-432]: https://ctds-planx.atlassian.net/browse/GQE-432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Skip RAS tests for Gen3-Helm if not a nightly-build PR

.secrets.baseline, gen3-integration-tests/pages/workspace.py, gen3-integration-tests/services/audit.py, gen3-integration-tests/tests/test_audit_service.py, gen3-integration-tests/utils/gen3_admin_tasks.py
Link to JIRA ticket if there is one: [GQE-429](https://ctds-planx.atlassian.net/browse/GQE-429)
[GQE-429]: https://ctds-planx.atlassian.net/browse/GQE-429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Increase timeouts for workspace, audit service and etl

gen3-integration-tests/tests/test_pfb_export.py
Link to JIRA ticket if there is one: [GQE-433](https://ctds-planx.atlassian.net/browse/GQE-433)
[GQE-433]: https://ctds-planx.atlassian.net/browse/GQE-433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Run Guppy mutation for PFB Export in gitops-qa

.github/workflows/shared_integration_tests.yaml
=> Trigger dependabot PRs manually

gen3-integration-tests/tests/test_audit_service.py
=> Fix Audit Tests Skip Logic

.github/workflows/shared_integration_tests.yaml
=> Clean up github workflow

gen3-integration-tests/tests/test_discoverypage.py, gen3-integration-tests/tests/test_pfb_export.py
=> Add sower marker to required tests

gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-generate-api-keys.groovy
=> Fix ci-only-generate-api-keys retry logic

.github/workflows/image_build.yaml, gen3-integration-tests/gen3_ci/scripts/generate_slack_report.py
=> Add nightly-run label when replaying nightly-build PRs

gen3-integration-tests/conftest.py, gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-check-register-users-on.groovy, gen3-integration-tests/pages/exploration.py, gen3-integration-tests/pages/login.py, gen3-integration-tests/tests/test_register_user.py, gen3-integration-tests/utils/gen3_admin_tasks.py
=> Fix Register User tests

gen3-integration-tests/tests/test_data_upload.py
Link to JIRA ticket if there is one: [GQE-457](https://ctds-planx.atlassian.net/browse/GQE-457)
[GQE-457]: https://ctds-planx.atlassian.net/browse/GQE-457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Change user for Data Upload Portal Test

gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-check-register-users-on.groovy, gen3-integration-tests/pages/exploration.py
=> Handle Multiple buttons on Midrc Exploration page

gen3-integration-tests/gen3_ci/scripts/select_ci_environment.py
=> Add hostname to adminvm envs in helm-based CI pipeline

gen3-integration-tests/gen3_ci/scripts/select_ci_environment.py
=> Backward compatible hostname setting for adminvm CI

.github/workflows/integration_tests.yaml, .github/workflows/shared_integration_tests.yaml, gen3-integration-tests/gen3_ci/scripts/select_ci_environment.py
=> Fix hostname for adminvm CI

gen3-integration-tests/utils/gen3_admin_tasks.py, gen3-integration-tests/utils/test_setup.py
=> Handle multiple jobs

gen3-integration-tests/gen3_ci/scripts/prepare_ci_environment.py, gen3-integration-tests/tests/test_data_upload.py
=> Add ssjdispatcher/sower markers and support for wts in env setup script

gen3-integration-tests/scripts/helm/env_setup.sh
=> Add logic for skip service image update for certain service repos

gen3-integration-tests/scripts/helm/env_setup.sh
=> Pelican sower job image update

gen3-integration-tests/scripts/helm/env_setup.sh
=> Update indexs3client image for indexs3client repo CI run

.github/workflows/integration_tests.yaml, .github/workflows/shared_integration_tests.yaml, gen3-integration-tests/gen3_ci/scripts/prepare_ci_environment.py
Link to JIRA ticket if there is one: [GQE-501](https://ctds-planx.atlassian.net/browse/GQE-501)
[GQE-501]: https://ctds-planx.atlassian.net/browse/GQE-501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Handle data-simulator CI

gen3-integration-tests/gen3_ci/default_manifest/values/values.yaml
Link to JIRA ticket if there is one: [GQE-504](https://ctds-planx.atlassian.net/browse/GQE-504) [GQE-505](https://ctds-planx.atlassian.net/browse/GQE-505)
[GQE-504]: https://ctds-planx.atlassian.net/browse/GQE-504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GQE-505]: https://ctds-planx.atlassian.net/browse/GQE-505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add Argo-wrapper and cohort-middleware services to default ci manifest

.github/workflows/integration_tests.yaml, gen3-integration-tests/scripts/helm/env_setup.sh
Link to JIRA ticket if there is one: [GQE-486](https://ctds-planx.atlassian.net/browse/GQE-486)
[GQE-486]: https://ctds-planx.atlassian.net/browse/GQE-486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix google_enabled for oauth2 tests

gen3-integration-tests/scripts/helm/env_setup.sh, gen3-integration-tests/tests/test_google_data_access.py, gen3-integration-tests/tests/test_oauth2.py, gen3-integration-tests/utils/gen3_admin_tasks.py
=> Fix is_google_enabled logic

gen3-integration-tests/gen3_ci/gcp_cleanup/Dockerfile, gen3-integration-tests/gen3_ci/gcp_cleanup/cleanup_google_resources.md, gen3-integration-tests/gen3_ci/gcp_cleanup/main.py, gen3-integration-tests/gen3_ci/gcp_cleanup/requirements.txt, gen3-integration-tests/gen3_ci/helm_cleanup/helm-ci-cleanup.yaml
Cloud Runner script can now be used to cleanup automatically generated resources in GCP from the CI runs.
=> adding the GCP "cloud run" script to gen3-code-vigil for documentation and reference.

gen3-integration-tests/pages/exploration.py, gen3-integration-tests/tests/test_register_user.py
=> Skip RegisterUser Test

gen3-integration-tests/scripts/helm/env_setup.sh
=> Update SED command to update FRAME_ANCESTOR

gen3-integration-tests/gen3_ci/scripts/prepare_ci_environment.py
=> Add integration tests to gen3-helm repo

gen3-integration-tests/pyproject.toml, gen3-integration-tests/tests/test_data_upload.py, gen3-integration-tests/tests/test_graph_submit_and_query.py, gen3-integration-tests/tests/test_presigned_url.py
=> Add gen3sdk label

gen3-integration-tests/pages/discovery.py, gen3-integration-tests/pages/login.py, gen3-integration-tests/services/ras.py, gen3-integration-tests/tests/test_audit_service.py
=> Nightly Build fixes

gen3-integration-tests/scripts/helm/env_setup.sh
Link to JIRA ticket if there is one: [GQE-518](https://ctds-planx.atlassian.net/browse/GQE-518)
[GQE-518]: https://ctds-planx.atlassian.net/browse/GQE-518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Move portal block into separate portal.yaml file

.github/workflows/shared_integration_tests.yaml
=> Fix nightly run

gen3-integration-tests/scripts/helm/env_setup.sh
=> Fix user-namespace issue for hatchery

gen3-integration-tests/gen3_ci/helm_cleanup/helm-ci-cleanup.yaml, gen3-integration-tests/scripts/helm/env_setup.sh
=> Delete indexd-userdb for nightly-build and update helm cleanup script

.github/workflows/shared_integration_tests.yaml
=> Fix sequence of steps

gen3-integration-tests/gen3_ci/scripts/setup_ci_env.sh
=> Fix Portal customConfig based setup changes

.github/workflows/shared_integration_tests.yaml
=> Allow 20 concurrent CI runs

gen3-integration-tests/tests/test_workspace.py
Link to JIRA ticket if there is one: [GQE-528](https://ctds-planx.atlassian.net/browse/GQE-528)
[GQE-528]: https://ctds-planx.atlassian.net/browse/GQE-528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Terminate hanging workspace before launching a new one

gen3-integration-tests/gen3_ci/scripts/setup_ci_env.sh
=> Add resouces to etl block on manifest setup

gen3-integration-tests/gen3_ci/scripts/setup_ci_env.sh
=> Pull useAggMds value from incoming manifest

.github/workflows/test_external_pr.yaml
=> Workflow to test external PR

gen3-integration-tests/gen3_ci/helm_cleanup/helm-ci-cleanup.yaml
Variable order needed to be changed in order for the SNS unsubscribe command to work.
=> fixing sns unsubscribe

gen3-integration-tests/tests/test_user_data_library.py
Link to JIRA ticket if there is one: [GQE-375](https://ctds-planx.atlassian.net/browse/GQE-375)
[GQE-375]: https://ctds-planx.atlassian.net/browse/GQE-375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add test case for gen3-user-data-library

.github/workflows/shared_integration_tests.yaml
=> Make QA_DASHBOARD_S3_PATH optional

.github/workflows/shared_integration_tests.yaml, gen3-integration-tests/gen3_ci/scripts/generate_slack_report.py
=> Disable GH Logs
